# Numpy
Numpy can be significantly faster than list

In [1]:
import numpy as np
myarr = np.arange(1_000_000)
mylist= list(range(1_000_000))

In [2]:
%timeit myarr2= myarr*2

1.06 ms ± 27.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit mylist2 = [ 2*x for x in mylist]

57 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## the ndarray object

In [14]:
import numpy as np
data = [[1.5, -0.1, 3],[0, -3, 6.5]]
arr = np.array(data)

In [15]:
arr

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [16]:
arr*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [17]:
arr+arr

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [18]:
arr.shape

(2, 3)

In [19]:
arr.ndim

2

In [20]:
arr.dtype

dtype('float64')

In [21]:
# numpy infers the data type
data2 = [ [1, 2, 3, 4], [5, 6, 7, 8] ]
arr2 = np.array(data2)

In [22]:
arr2.dtype

dtype('int32')

In [23]:
# create arrays of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
# create array without initialize its values:
np.empty((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [28]:
# create an array with the same shape of the given argument, filled with zeros or ones
print(arr2)
np.zeros_like(arr2)

[[1 2 3 4]
 [5 6 7 8]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
# create an array of the given size, initialized to a given value
np.full((2,4),5.0)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [33]:
np.full_like(arr2,5.0) # by default use the same datatype of arr2

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [36]:
# Creating a matrix with a diagonal of ones
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [39]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [40]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
# np.eyes is a more flexible version of np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Datatypes

numpy supports different datatypes:
- int8, int16, int32, int64 (type code: i1, i2, i4, i8)
- uint8, uint16, uint32, uint64 (type code: u1, u2, u4, u8)
- float16, float32, float64, float128 (type code: f2, f4 or f, f8 or d, f16 or g)
- complex64, complex128, complex256 (type code: c8, c16, c32)
- bool (type code: ?)
- object (type code: O)
- string_ (type code: S | fixed length ascii string type. To create a string with 10 character use S10)
- unicode_ (type code: U | fixed length unicode string type. To create a string with 10 character use U10))

In [43]:
arr =np.array(range(1,6))

In [44]:
arr

array([1, 2, 3, 4, 5])

In [45]:
arr.dtype

dtype('int32')

In [46]:
# astype can be used to do type conversion
float_arr = arr.astype(np.float64)

In [48]:
float_arr.dtype

dtype('float64')

In [50]:
arr_float = np.array([3.2, 4.5, 6.7])
arr_float

array([3.2, 4.5, 6.7])

In [51]:
arr_int = arr_float.astype(np.int32)

In [52]:
arr_int

array([3, 4, 6])

In [68]:
# astype can convert also strings
arr_str = np.array(["3.2", "4.57", "123.12"], dtype=np.string_)

In [69]:
arr_str

array([b'3.2', b'4.57', b'123.12'], dtype='|S6')

In [61]:
arr_str.dtype

dtype('S6')

In [62]:
arr_str.astype(np.float32)

array([  3.2 ,   4.57, 123.12], dtype=float32)

In [63]:
# the type code can be used as shorthand to identify data types
zeros_uint32 = np.zeros(4, dtype="u4")

In [64]:
zeros_uint32.dtype

dtype('uint32')

In [66]:
arr_str2 = np.array(["3.2", "4.57", "123.12"], dtype="S7")

In [67]:
arr_str2

array([b'3.2', b'4.57', b'123.12'], dtype='|S7')

## Arithmetic with numpy arrays

In [70]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [71]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [72]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [73]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [75]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [76]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [77]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [79]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# basic indexing and slicing

In [80]:
arr =np.arange(10)

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[5]

5

In [83]:
arr[5:8]

array([5, 6, 7])

In [84]:
# numpy supports propagation
arr[5:8] = 12

In [85]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [86]:
# note the difference with lists:

In [87]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [88]:
mylist[5:8]

[5, 6, 7]

In [89]:
# with list there is no propagation, this gives an error
mylist[5:8] = 12

TypeError: can only assign an iterable

In [90]:
# you should do: 
mylist[5:8] = [12,12,12]

In [91]:
mylist

[0, 1, 2, 3, 4, 12, 12, 12, 8, 9]

In [101]:
# moreover any view on an array points to the original array, it doesn't create a copy, so this happens:
arr_slice = arr[5:8]
arr_slice

array([   12, 12345,    12])

In [102]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [103]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [104]:
# with list, the slice is a copy so in that case it would be:
list_slice = mylist[5:8]
list_slice

[12, 12, 12]

In [105]:
list_slice[1]=12345
list_slice

[12, 12345, 12]

In [106]:
mylist

[0, 1, 2, 3, 4, 12, 12, 12, 8, 9]

In [108]:
# to create a copy of an array from a slice, you should explicitly create a copy:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([   12, 12345,    12])

In [109]:
arr_slice2[:] = 64
arr_slice2

array([64, 64, 64])

In [110]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [112]:
# in two dimensional array, the elements at each index are no longer scalars but one dimensional arrays,
# you can access them with a single index
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [113]:
arr2d[2]

array([7, 8, 9])

In [114]:
# then you can recursively enter the element of the array you extracted
arr2d[2][1]

8

In [115]:
#which is equivalent to:
arr2d[2,1]

8

In [116]:
# same principle works for n-dimensional array, e.g.
arr3d = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr3d[0,0]

array([1, 2, 3])

In [119]:
arr3d[0,:,0]

array([1, 4])

In [120]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
# Note that slicing maintains the same number of dimensions of the original array
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
arr2d[2:]

array([[7, 8, 9]])

In [124]:
arr2d[2:].shape

(1, 3)

In [125]:
# indexing on the other hand select a specific element in the ndarray, so it reduce the dimensionality:
arr2d[2]

array([7, 8, 9])

In [126]:
arr2d[2].shape

(3,)

In [127]:
# you can mix things up:
arr2d[1,:2]

array([4, 5])

In [129]:
arr2d[1,:2].shape

(2,)

### Boolean indexing

In [134]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [138]:
data = np.array([[4,7], [0,2], [-5,6], [0,0], [1,2], [-12,-4], [3,4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [136]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [137]:
# the Boolean array created above can be used to indexing the data array
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [144]:
data[names=="Bob",1]

array([7, 0])

In [145]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [146]:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [150]:
# The tilde operator can be used to invert a Boolean array
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [151]:
cond = names == "Bob"

In [152]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [153]:
# To combine multiple conditions use the operator "&" and "|". 
#Note that the python operators "and" and "or" DO NOT work with boolean arrays

mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [154]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [155]:
# Boolean indexing can be used also to set values:
data < 0

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [156]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [157]:
data[data<0]=0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

### Fancy indexing

In [158]:
# you can pass a list or a ndarray of integers to select multiple elements from the array
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [159]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [160]:
# negative indices select rows from the end
arr[[-1,-3,-7]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.]])

In [168]:
# passing multiple index arrays selects a one dimensional array of elements corresponding to each tuple of indices
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [163]:
arr[ [1,5,7], [0,3,2] ]

array([ 4, 23, 30])

In [164]:
# note the difference with:
arr[[1,5,7]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [165]:
arr[[1,5,7]][:,[0,3,2]]

array([[ 4,  7,  6],
       [20, 23, 22],
       [28, 31, 30]])

In [181]:
# Differently from slicing
# Fancy indexing creates a new array, which is a copy of the original one, so you can assign value to this copy
# without affecting the original one. 

# so if you do:
fancy_sel =arr[ [1,5,7], [0,3,2] ] 
fancy_sel


array([ 4, 23, 30])

In [182]:
fancy_sel.ndim

1

In [183]:
fancy_sel = [0,0,0]
fancy_sel

[0, 0, 0]

In [184]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [185]:
# however, you can use fancy selection to assign values to the original array directly
arr[ [1,5,7], [0,3,2] ] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28, 29,  0, 31]])

### Transpose arrays, Swapping Axes and inner matrix multiplication

In [186]:
arr = np.arange(15).reshape((3,5))

In [187]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [188]:
# Transpose with T
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [189]:
# inner product with np.dot
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [190]:
# Same can be done with @
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [191]:
# Transposition is a special case of axes swapping, which can be done with swapaxes:
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Pseudo random number generation

In [192]:
samples = np.random.standard_normal(size=(4,4))

In [193]:
samples

array([[-0.63779562,  0.22102783,  0.83519171,  0.05740515],
       [-1.75556494,  0.37322504, -1.18490875, -0.47532665],
       [ 0.47479481, -0.77636973, -0.5138079 ,  0.26130184],
       [ 0.03440861, -1.81958499, -0.17219458, -0.77629908]])

In [195]:
# numpy number generator is way faster than python random
from random import normalvariate
N = 1_000_000


In [196]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

658 ms ± 14.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [197]:
%timeit samples = np.random.standard_normal(N)

20.6 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [198]:
# numpy.random.standard_normal use the numpy.random default random number generator. 
# You can explicit the random number generator to use, and configure it this way:
rng = np.random.default_rng(seed=12345)

In [199]:
data = rng.standard_normal((2,3))

In [201]:
seq = np.arange(10)
seq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [204]:
rng.permutation(seq)

array([0, 8, 3, 7, 2, 6, 9, 5, 4, 1])

In [205]:
seq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
seq2 = seq.copy()

In [207]:
seq2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
rng.shuffle(seq2)
seq2

array([2, 4, 3, 7, 8, 1, 9, 6, 0, 5])

In [210]:
rng.uniform(low=-10., high=10., size=(2,3))

array([[ 6.31552807, -6.13411221, -7.41061848],
       [-8.16670497,  1.97136027,  7.09483809]])

In [213]:
rng.integers(low=-10, high=10, size=(2,3), endpoint=True) # endpoint specifies if high could be included (true) or not (false)

array([[-5, -5,  9],
       [ 1,  0, -4]], dtype=int64)

In [215]:
rng.standard_normal(size=(2,3))

array([[ 0.31290292, -0.13081169,  1.26998312],
       [-0.09296246, -0.06615089, -1.10821447]])

In [216]:
rng.normal(loc=-1.0, scale= 2.0, size=(2,3) ) # Normal distribution N(loc, scale^2)

array([[-0.7280863 ,  1.69415553, -0.87771196],
       [-0.8581708 , -0.13269093, -0.44503268]])

## ufunc - Universal functions

### unary ufuncs
Are simple element wise transformations

In [217]:
arr = np.arange(10)

In [218]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [219]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### binary ufuncs
take two arrays in input and return a single array.

In [224]:
x = rng.integers(0,high=10,size=10)
x

array([2, 9, 2, 6, 2, 8, 4, 5, 2, 6], dtype=int64)

In [226]:
y = rng.integers(0,10,size=10)
y

array([1, 2, 7, 3, 6, 8, 2, 8, 7, 3], dtype=int64)

In [229]:
z = np.add(x, y)
z

array([ 3, 11,  9,  9,  8, 16,  6, 13,  9,  9], dtype=int64)

In [230]:
np.maximum(x,y)

array([2, 9, 7, 6, 6, 8, 4, 8, 7, 6], dtype=int64)

In [231]:
arr = rng.standard_normal(7)*5

In [232]:
arr

array([-1.58695973, -4.07907483,  1.93289509, -1.11819463, -3.50845404,
       -8.97856588,  4.09162811])

In [233]:
remainder, wholepart = np.modf(arr)

In [234]:
remainder

array([-0.58695973, -0.07907483,  0.93289509, -0.11819463, -0.50845404,
       -0.97856588,  0.09162811])

In [235]:
wholepart

array([-1., -4.,  1., -1., -3., -8.,  4.])

In [238]:
np.abs(arr)

array([1.58695973, 4.07907483, 1.93289509, 1.11819463, 3.50845404,
       8.97856588, 4.09162811])

In [240]:
np.sqrt(x)

array([1.41421356, 3.        , 1.41421356, 2.44948974, 1.41421356,
       2.82842712, 2.        , 2.23606798, 1.41421356, 2.44948974])

In [241]:
np.square(x)

array([ 4, 81,  4, 36,  4, 64, 16, 25,  4, 36], dtype=int64)

In [242]:
np.log(x) # natural log

array([0.69314718, 2.19722458, 0.69314718, 1.79175947, 0.69314718,
       2.07944154, 1.38629436, 1.60943791, 0.69314718, 1.79175947])

In [243]:
np.log10(x)

array([0.30103   , 0.95424251, 0.30103   , 0.77815125, 0.30103   ,
       0.90308999, 0.60205999, 0.69897   , 0.30103   , 0.77815125])

In [244]:
np.log2(x)

array([1.        , 3.169925  , 1.        , 2.5849625 , 1.        ,
       3.        , 2.        , 2.32192809, 1.        , 2.5849625 ])

In [245]:
np.log1p(x) # compute logn(1+x)

array([1.09861229, 2.30258509, 1.09861229, 1.94591015, 1.09861229,
       2.19722458, 1.60943791, 1.79175947, 1.09861229, 1.94591015])

In [246]:
np.sign(arr)

array([-1., -1.,  1., -1., -1., -1.,  1.])

In [247]:
np.ceil(arr)

array([-1., -4.,  2., -1., -3., -8.,  5.])

In [248]:
np.floor(arr)

array([-2., -5.,  1., -2., -4., -9.,  4.])

In [249]:
np.rint(arr)

array([-2., -4.,  2., -1., -4., -9.,  4.])

In [250]:
np.isnan(arr) # checks for NaN values

array([False, False, False, False, False, False, False])

In [251]:
np.isinf(arr) # checks for Infinite values

array([False, False, False, False, False, False, False])

In [252]:
np.power(x,y) # compute x^y element wise

array([       2,       81,      128,      216,       64, 16777216,
             16,   390625,      128,      216], dtype=int64)

In [253]:
np.mod(x,y) # element wise modulus

array([0, 1, 2, 0, 2, 0, 0, 5, 2, 0], dtype=int64)